version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: personal_finance_tracker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: finance_user
      MYSQL_PASSWORD: finance_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: personal-finance-tracker
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/personal_finance_tracker
      SPRING_DATASOURCE_USERNAME: finance_user
      SPRING_DATASOURCE_PASSWORD: finance_pass
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
